# Generated by Django 5.2.1 on 2025-12-29 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpoCeleste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('star', 'Estrela'), ('planet', 'Planeta'), ('moon', 'Lua')], max_length=10)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('distancia', models.CharField(blank=True, max_length=100)),
                ('diametro', models.CharField(blank=True, max_length=100)),
                ('massa', models.CharField(blank=True, max_length=100)),
                ('temperatura', models.CharField(blank=True, max_length=100)),
                ('composicao', models.TextField(blank=True)),
                ('curiosidades', models.TextField()),
                ('planeta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luas', to='core.corpoceleste')),
            ],
        ),
    ]
