# Generated by Django 5.2.1 on 2026-01-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpoceleste',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='corpos_celestes/'),
        ),
    ]
