# Generated by Django 5.2.1 on 2026-01-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corpoceleste_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpoceleste',
            name='categoria',
            field=models.CharField(choices=[('estrela', 'Estrela'), ('planeta', 'Planeta'), ('lua', 'Lua')], max_length=10),
        ),
    ]
