# Generated by Django 5.2.1 on 2026-01-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_corpoceleste_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpoceleste',
            name='composicao',
        ),
        migrations.AlterField(
            model_name='corpoceleste',
            name='planeta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='luas', to='core.corpoceleste'),
        ),
    ]
